### ISSUE TITLE
testsuite

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#169]
we need to clean up the files in the test suite; as of now, it is not helpful for a (new) user;

i'd like each folder to have a README that explains the tests and also for files to be organized in subfolders and numbered, e.g., testChinese/0_chinesePunct.txt, etc.

**Comment by JingxianL** [comment]
The README file in Classical Chinese folder isn't correct. The file that is in the FileToUse is not mentioned in the readme file, and the file that is mentioned is currently not in the FileToUse.

**Comment by akuisara** [comment]
Old files were probably accidentally deleted, I just re-added those files mentioned in README from last year's repo. But we need to re-write the README.

**Comment by mleblanc321** [comment]
hmmm, why all these files with tilda(~) at the end in the TestSuite folders?

jingxian: can you read over/edit the Classical and Modern Chinese directions

shiwei: the TestSuite/Scrubber/ folder still has too many files in it; we also need a README to describe what is in each folder (e.g., what is Apos/ ?  i know, but explain to the reader);

jesse: i think digits/ still needs some organization ... including a README that explains to a new person why they might upload these files

**Comment by akuisara** [comment]
Those files with tilda are probably temp backup files created by editors. Adding a line "*~" in .gitignore should be able to ignore those files.

**Comment by jaronson13** [comment]
On Friday I organized the digits folder and made a README. It's ready to push anytime.

**Comment by scottkleinman** [comment]
Those deleted Chinese files continue to cause conflicts for me. While they are in the repo, I can't commit or push anything. So I have temporarily removed them again until we can figure out the problem. I have some theories. One is the spaces in the folder names "Classical Chinese" and "Modern Chinese". Another is spaces and/or commas in the file names. We should re-add the folders and files gradually until we can see what is generating the conflict.

**Comment by chantisnake** [comment]
Hi scott:

You probably need to do ````git pull```` before you do ````git push````

**Comment by scottkleinman** [comment]
I tried that, but the problem seems to be related to those files. I deleted the entire repo, uninstalled and re-installed git, and they always come back--unless I delete them from the repo (which also doesn't always work). Since I've managed to get them out of the repo now, I'm going to start adding them back one by one to see if the problem returns. But I'll be sure to do another `git pull` first.

**Comment by scottkleinman** [comment]
This issue is now resolved on my end. (That is, I can now commit and push to the repo.) I have, I hope, restored the Chinese files to the repo, except that I have removed the space in "Classical Chinese" and "Modern Chinese" in the folder names. If the files are not what they should be, please let me know, and I'll see if I omitted anything.

I'm not sure if the original issue, which had to do with documentation of the test material, has been resolved, so I am leaving this issue open.

**Comment by JingxianL** [comment]
I think somehow the files were deleted again, so I re-added them. But I still need Sara to add the Classical Chinese files onto the repo. @akuisara

**Comment by ShiweiJuliaHuang** [comment]
I just updated Readme.md for the Scrubber file. Let me know how this can be improved.

**Comment by mleblanc321** [comment]
shiwei: let's chat about cleaning up the TestSuite/Experiments/ directory (and addressing the issues scott was having with some of the files and/or filenames (note:  all files should use underscores and/or camelCase, and not spaces)

**Comment by scottkleinman** [comment]
I think we need to take this up urgently. I still cannot push to GitHub or even commit my changes because of this issue.

**Comment by mleblanc321** [comment]
grrr.....

**Comment by mleblanc321** [comment]
i removed the Experiments/Chinese folder and pushed;  i'll try to clean up and put back (but i'll wait until i hear if you can now pull/push)

**Comment by scottkleinman** [comment]
And voila: [https://github.com/WheatonCS/Lexos/commit/113c6bdd8ed925b26b6887d863ce77d32388b7a4](https://github.com/WheatonCS/Lexos/commit/113c6bdd8ed925b26b6887d863ce77d32388b7a4)!

**Comment by scottkleinman** [comment]
This issue was never closed. Do we need to do any more documentation for the tests?

**Comment by mleblanc321** [comment]
>>Jingxian said earlier:
The README file in Classical Chinese folder isn't correct. The file that is in the FileToUse is not mentioned in the readme file, and the file that is mentioned is currently not in the FileToUse.

** sara: please look over our collection of Chinese examples and prune/organize as needed; push;

**Comment by akuisara** [comment]
Just pushed the changes

**Comment by scottkleinman** [comment]
We may need a re-organisation post summer 2016, but I think we can close this issue.
