### ISSUE TITLE
Select Page highting not working right

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#202]
There is a problem that I am keep experiencing on my local machine, but not that much with the live version. The highlight most of the time does not work correctly untill I manually hard refresh the page. For example, if I have all the file first unactive and click on the first file in the list, to active it, then click on the second one, somehow the green highlight will be gone and only highlight the second one. But if I refresh the page, then it will change to highlight both the first and second one. Another problem is that, if I have a file that is active first, and I click on it to deactivate the file, there will be a post sending through, but the color does no change untill I refresh the page. But the user will then think the file is not deactivate. and click on it again, which then would actually enable the file, but show on screen as disabled.

**Comment by scottkleinman** [comment]
I wonder if the fix for Select All/Deselect all somehow triggered this. I'll look into it.

**Comment by scottkleinman** [comment]
I apparently pushed a version of base.html that had the code to load JQuery UI from CDN commented out. Instead, it was trying and failing to load a local version. At least, that is what my local copy of base.html had. In the version on GitHub, the code is right. You may just need to do another pull. On my end, in trying to fix it, I have messed up my local GitHub repo again, so I can't push or pull until I figure out what is wrong.

**Comment by scottkleinman** [comment]
OK, I've merged my local repo with the remote one, but I'm still encountering the problem. So I'll continue to investigate...

**Comment by scottkleinman** [comment]
I don't know why this behaviour didn't show up until now, but it looks like it may take some substantial re-writing. I'm going to move off the master branch for this one...

**Comment by JingxianL** [comment]
I wasn't sure why this happens, but I am sure that the post did send through and it is just the front end is somehow not responding.

**Comment by scottkleinman** [comment]
Yes, it's definitely front end. I just pushed a fix which seems to work for me. Please test.

**Comment by JingxianL** [comment]
I think now the problem is, it still doesn't respond to the highlight, but when I reload, it will go back to select all. So I still think there is something not working right,

**Comment by scottkleinman** [comment]
I've pushed another fix. Let me know if the problems continue.

**Comment by scottkleinman** [comment]
It's still not working. It seems that the UI is not keeping styles consistently or that there is a delay before the styles are updated. I'll keep working.

**Comment by scottkleinman** [comment]
I think I have a fix for the UI, but I need to handle the back end. I'm pulling the new file manager code today to look at what's involved.

**Comment by chantisnake** [comment]
I did not move the file manager, just rename that into ````FIleManager.py````

**Comment by scottkleinman** [comment]
Yes, I noticed that. Everything in Select is now working in my local test installation. Due to issue #221, I'm going to hold off on pushing until this afternoon.

**Comment by scottkleinman** [comment]
I have now pushed the fixes. Please test. If there are no problems, I will close this issue tomorrow.

Be advised that there is one bug in the code. If you load the page with the first table row selected, shift-click will not work starting from that row. You have to click on it first. This seems to be a bug in all the shift-click implementations I could find that will also work with JQuery UI Selectable (the drag select function). It seems acceptable to me to let this go for the moment. I think in the next release we're going to have to re-think the UI anyway.

**Comment by JingxianL** [comment]
I just pulled this morning, and I still don't think it is working correctly. The problem with when selecting file highting is still not correct, it only select the one that I click on. Also there is an weird error appear sometimes saying that your current change can't save to session.

**Comment by scottkleinman** [comment]
The behaviour now is to select only the clicked file when you click. To keep other files from deselecting, use shift-click or control-click, or drag the cursor over a range of files. If this is not intuitive, we may need to reconsider. All the shift-click functions do this.

However, there are two other problems. The Select All and Deselect All functions only work on the current page. I'll look into that later today.

For me, the Ajax errors only occur after I have deleted I file. I probably need a routine to re-build the client-side array of enabled documents. I'll work on this as well.

Let me know if you experience problems other than the above.

**Comment by scottkleinman** [comment]
Since we're going to a new model, I'm going to close this issue. We can always re-open it if we need to re-use the current version.
