### ISSUE TITLE
HTML MUFI 3.0/4.0 entity vs character issue

### ISSUE THREAD

**Issue by JordanHelpsAlot** [WheatonCS/Lexos#355]
Please give us some of the following information, 
That will be really helpful to track the bug:

* Not a new thing, just putting this on Github

* **if you are proposing an enhancement, please delete all of these**

### which option did I click
On scrub page, special character description link

### which file did I use
Not relevant

### what the bug looks like
Unicode reference sheet is translating ascii pattern into characters on the fly

### what I expect to happen
Entity name should not include the actual character

### how to reproduce it
Follow the link: http://localhost:5000/static/html/pre_defined_rules.html#mufi-3.0

**Comment by scottkleinman** [comment]
I think this issue should be solved after we divide up the different rule sets into multiple pages. That'll make it easier to work with. I'll assign this one to myself.

**Comment by kreddy95** [comment]
In the 4.0 one it seems that the browser is also interpreting the unicode code point incorrectly but it seems be be working fine for 3.0
ex. if it is supposed to be 00E4 the browser turns it into 0.00E+00
or if it is supposed to be 0061 it turns it into 61

**Comment by chantisnake** [comment]
856c1b2dbf5aeb4b114f6dcdf5abaf3cacc72e31 here is the commit.

Now that I have noticed that there is one extra file that is commited in this commit. Would any one please remove that?

We really need to see all the file we committed before push.

**Comment by chantisnake** [comment]
Can we still reproduce this now? I think everything related to scrub is fixed.

**Comment by scottkleinman** [comment]
I think it's still an issue for a limited number of characters. Let's get an update from Kristina tomorrow.

**Comment by chantisnake** [comment]
I don't really understand what this issue is saying... Is it possible to show me an example?

Also I think me and Kristina fixed all the mufi bugs together. When I ask her she says all the mufi bug is fixed. But it is possible that she forget about this.

**Comment by kreddy95** [comment]
Yes this is still a bug, we never did anything related to the view pre-defined rule sets link

**Comment by chantisnake** [comment]
krastina is on it! 

fixing it by hand, I think we can expext her to fix it by the end of this morning, maybe...

**Comment by chantisnake** [comment]
@scottkleinman I think you make it via a script, can you send us the script you use?

because this bug will be so hard to fix without a script.

**Comment by kreddy95** [comment]
d2a0b6ef96b1687e3a92cfde13d2e1574f3a5397
In this commit I changed alot of the entities so they show up as they should on the browser (im pretty sure they all work I could be wrong there are alot that I didnt change still but the ones I saw as an issue displaying were changed) I added &amp; so it doesnt escape the ampersand character in the entity names.
There has been nothing done about the unicode code points for MUFI 4.

**Comment by kreddy95** [comment]
The official mufi tables are already linked to the pdf at the top of each table for them so if they have issues they can always go to that for now to see it instead of completely taking out the tables

**Comment by scottkleinman** [comment]
The html tables have been split into multiple files and they display the characters in Junicode. I think the only thing left to do is proofread the MUFI tables. For clarity, I'll open that as a separate issue.
