### ISSUE TITLE
visualizations no longer functioning

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#403]
wordcloud and bubbleviz no longer generate graphs. If any number of files are checked they become unchecked on the get graph button. This is brand new and a huge deal.

**Comment by scottkleinman** [comment]
Putting out fires as fast as I can. So far, I've determined that there are no Python or Javascript error messages. I'll start digging now.

**Comment by scottkleinman** [comment]
OK, I've definitely found the problem. Working on a fix.

**Comment by SocialHulkHogan** [comment]
thanks a ton

**Comment by scottkleinman** [comment]
OK, I've fixed Word Cloud. Can you pull and test it to make sure it is working your end? Once you confirm, I'll fix BubbleViz.

The problem was that I had switched the button from `<input type="submit">` to `<a class="btn">`. `$("form").submit()` will not work unless you have `<input type="submit">`. I never noticed this because I was always using the `<a>` element to trigger an ajax function.

**Comment by scottkleinman** [comment]
OK, BubbleViz was a little more complicated, but I've pushed a fix.

**Comment by SocialHulkHogan** [comment]
This doesn't appear to be fixed. I just pulled, restarted local host, ctrl shift r in the browser and it still isn't creating the vizulaizations.

**Comment by SocialHulkHogan** [comment]
wordcloud works in firfox, bubbleviz seems to be still broken

**Comment by scottkleinman** [comment]
I think this could be a browser issue. It is working for me on Firefox, but not on Chrome. I have an idea of how to fix it.

**Comment by scottkleinman** [comment]
Looks like Chrome was insisting on treating the submit as a GET request. I changed the method right before the form submission. Try pulling and let me know if it works for you.

**Comment by SocialHulkHogan** [comment]
brilliant it works now.

**Comment by scottkleinman** [comment]
Yippee!

**Comment by evanlaferriere** [comment]
Not that this doesn't work-
But I got this:
```
127.0.0.1 - - [29/Jun/2016 15:30:12] "POST /viz HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
    self.send_header(key, value)
  File "/home/lexos/anaconda2/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
127.0.0.1 - - [29/Jun/2016 15:30:17] "POST /viz HTTP/1.1" 200 -
```
In the python terminal when I successfully got a graph. Why's that happening?

**Comment by SocialHulkHogan** [comment]
I had that too once. probably some refresh stuff

**Comment by chantisnake** [comment]
broken pip is python lost the pipline with apache, I think.

Which is none related.
