### ISSUE TITLE
tokenize not working with tags

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#411]
what it sounds like, the table will not display for files that have not been scrubbed of their tags, it seems

**Comment by scottkleinman** [comment]
Hmmm... I'll test this. It may apply everywhere we use DataTables.

**Comment by scottkleinman** [comment]
I'm trying Dan. The Table displays all right, but searching for "corr" or "<corr>" doesn't provide any results.

**Comment by evanlaferriere** [comment]
I figured this out with genesis, if an unscrubbed version would appear in the table, the table fails to build, no error.

**Comment by scottkleinman** [comment]
OK, I see that as well. I wonder if that's because it is a .sgml file and Dan is a text file? I'll keep testing.

**Comment by chantisnake** [comment]
I will look into this

**Comment by evanlaferriere** [comment]
This seems to me to be a punctuation issue, as Green Eggs and Ham unscrubbed also fails to make a table

**Comment by evanlaferriere** [comment]
My column headers are switched. 
![screenshot](https://cloud.githubusercontent.com/assets/17057324/16462347/d7555a86-3dfe-11e6-9cfc-fd16497d78e7.png)

**Comment by evanlaferriere** [comment]
What causes Green Eggs and Ham to fail is the line 
```
"Green Eggs and Ham" (by Doctor Seuss)
```
The " followed by ( is I've tested and this breaks the table. A file that consists of
```
"test" (test)
```
has the same effect. What could be causing this?

**Comment by evanlaferriere** [comment]
Using this xml file:
[LMWdbk_070071_Table.xml.txt](https://github.com/WheatonCS/Lexos/files/339877/LMWdbk_070071_Table.xml.txt)
Produces [this] (http://i.imgur.com/9xJcJtT.png) WTF

**Comment by scottkleinman** [comment]
LMWdbk_070071_Table.xml.txt produces a perfect table for me in both Firefox and Chrome. Can you post your Green Eggs and Ham text for me to test?

**Comment by evanlaferriere** [comment]
[Green Eggs and Ham.txt](https://github.com/WheatonCS/Lexos/files/339928/Green.Eggs.and.Ham.txt)

**Comment by scottkleinman** [comment]
OK. That crashes the table for me. It's definitely the quotation marks that are the problem. I'll see if they can be escaped.

**Comment by evanlaferriere** [comment]
weird thing is that a file that just says "test" will pass. but not "test" (test)

**Comment by scottkleinman** [comment]
Oh, this is evil. I have a fix, but I need to go through and make sure that it works for columns and rows in both orientations. I'll update here when I'm ready to push.

**Comment by evanlaferriere** [comment]
With two test files, one containing [test](https://github.com/WheatonCS/Lexos/files/339948/test.txt) and one containing ["test"](https://github.com/WheatonCS/Lexos/files/339949/test2.txt), can each be displayed on the table individually but not together. 
[Cat in the Hat](https://github.com/WheatonCS/Lexos/files/339951/Cat.in.the.Hat.txt) also cannot be displayed by itself. When uploaded together, CitH and "test" (aptly named test2) [switch columns](http://i.imgur.com/jBukwLC.png), if there are other file loaded but not active, this can fix itself.

**Comment by scottkleinman** [comment]
I've just pushed a fix. Let me know if it works for you.

**Comment by evanlaferriere** [comment]
I still can't generate a table with the punctuation cases but none of the headers have switched yet

**Comment by scottkleinman** [comment]
I am not encountering any of these phenomena with your test files. Perhaps a browser caching issue?

**Comment by evanlaferriere** [comment]
I'm still getting entire pages full of blanks for terms, using unscrubbed xml files

**Comment by scottkleinman** [comment]
It seems that this is still an issue. The problem is probably our tokenization regex.

**Comment by chantisnake** [comment]
I don't really understand what this issue is talking about, and how to reproduce this.

That screenshot looks like we forget to escape xml tag in the html we rendered...

I have a general function that can escape tags in html: [function `html_escape` at `general_function.py`](https://github.com/WheatonCS/Lexos/blob/master/helpers/general_functions.py#L235)

**Comment by scottkleinman** [comment]
I tried `html_escape`, but it didn't make much difference. The easiest way to reproduce the bug is by uploading `A1.1_GenAB_T00010.sgml`, do not scrub, and go straight to Tokenizer.

**Comment by chantisnake** [comment]
okay, I will try that.

**Comment by chantisnake** [comment]
I think the problem is related to html escaping.

Auh... I cannot upload pics here due to AWS is block... S***

I will fix this.

**Comment by chantisnake** [comment]
fixed in commit 25d3f84e6075cfe27c30a2dcef3d4b2cde1bd22a

It takes a long time because I forget to press `ctrl+R`...

**Comment by scottkleinman** [comment]
I disabled the upload script with a typo yesterday, and the problem didn't show up until today. Damn browser caching...
